# CMake generated Testfile for 
# Source directory: /Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib
# Build directory: /Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[CMakeLib.testArgumentParser]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testArgumentParser")
set_tests_properties([=[CMakeLib.testArgumentParser]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestBinPacker]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testCTestBinPacker")
set_tests_properties([=[CMakeLib.testCTestBinPacker]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestResourceAllocator]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testCTestResourceAllocator")
set_tests_properties([=[CMakeLib.testCTestResourceAllocator]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestResourceSpec]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testCTestResourceSpec" "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib")
set_tests_properties([=[CMakeLib.testCTestResourceSpec]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestResourceGroups]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testCTestResourceGroups")
set_tests_properties([=[CMakeLib.testCTestResourceGroups]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testGccDepfileReader]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testGccDepfileReader" "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib")
set_tests_properties([=[CMakeLib.testGccDepfileReader]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testGeneratedFileStream]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testGeneratedFileStream")
set_tests_properties([=[CMakeLib.testGeneratedFileStream]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testJSONHelpers]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testJSONHelpers")
set_tests_properties([=[CMakeLib.testJSONHelpers]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testRST]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testRST" "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib")
set_tests_properties([=[CMakeLib.testRST]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testRange]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testRange")
set_tests_properties([=[CMakeLib.testRange]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testOptional]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testOptional")
set_tests_properties([=[CMakeLib.testOptional]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testString]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testString")
set_tests_properties([=[CMakeLib.testString]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testStringAlgorithms]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testStringAlgorithms")
set_tests_properties([=[CMakeLib.testStringAlgorithms]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testSystemTools]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testSystemTools")
set_tests_properties([=[CMakeLib.testSystemTools]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUTF8]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testUTF8")
set_tests_properties([=[CMakeLib.testUTF8]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testXMLParser]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testXMLParser")
set_tests_properties([=[CMakeLib.testXMLParser]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testXMLSafe]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testXMLSafe")
set_tests_properties([=[CMakeLib.testXMLSafe]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testFindPackageCommand]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testFindPackageCommand")
set_tests_properties([=[CMakeLib.testFindPackageCommand]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVProcessChain]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testUVProcessChain" "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/testUVProcessChainHelper")
set_tests_properties([=[CMakeLib.testUVProcessChain]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVRAII]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testUVRAII")
set_tests_properties([=[CMakeLib.testUVRAII]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVStreambuf]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testUVStreambuf" "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/bin/cmake")
set_tests_properties([=[CMakeLib.testUVStreambuf]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMExtMemory]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testCMExtMemory")
set_tests_properties([=[CMakeLib.testCMExtMemory]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMExtAlgorithm]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testCMExtAlgorithm")
set_tests_properties([=[CMakeLib.testCMExtAlgorithm]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMExtEnumSet]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testCMExtEnumSet")
set_tests_properties([=[CMakeLib.testCMExtEnumSet]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testList]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testList")
set_tests_properties([=[CMakeLib.testList]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerAdapter]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testDebuggerAdapter")
set_tests_properties([=[CMakeLib.testDebuggerAdapter]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerAdapterPipe]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testDebuggerAdapterPipe")
set_tests_properties([=[CMakeLib.testDebuggerAdapterPipe]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerBreakpointManager]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testDebuggerBreakpointManager")
set_tests_properties([=[CMakeLib.testDebuggerBreakpointManager]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerVariables]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testDebuggerVariables")
set_tests_properties([=[CMakeLib.testDebuggerVariables]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerVariablesHelper]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testDebuggerVariablesHelper")
set_tests_properties([=[CMakeLib.testDebuggerVariablesHelper]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerVariablesManager]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLibTests" "testDebuggerVariablesManager")
set_tests_properties([=[CMakeLib.testDebuggerVariablesManager]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;79;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerNamedPipe-Project]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/testDebuggerNamedPipe" "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/bin/cmake" "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/DebuggerSample" "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/DebuggerSample")
set_tests_properties([=[CMakeLib.testDebuggerNamedPipe-Project]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;102;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerNamedPipe-Script]=] "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/testDebuggerNamedPipe" "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/bin/cmake" "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/DebuggerSample/script.cmake")
set_tests_properties([=[CMakeLib.testDebuggerNamedPipe-Script]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;102;add_test;/Users/wdelaros/Desktop/Cub3D/cmake-3.27.8/Tests/CMakeLib/CMakeLists.txt;0;")
subdirs("PseudoMemcheck")
